{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.customplugin",
    "module": "myplugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "e3woa5n3mzcbnd2jtdowpx4auu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myplugin-1.0.jar",
          "url": "myplugin-1.0.jar",
          "size": 16154,
          "sha512": "5c2dd4f2cecbf8101412b75fa957bd4b916873b69c08b49f4ba7b73981b54a36d237521df3980f73c8ecfd6e8c4853f94bead44835f66f79bbf4bb8c53f554ff",
          "sha256": "ed26181a9ee76e1d9ab6303f2ea0e5719ee55c023caec2f742b802aeb58ad0cb",
          "sha1": "470c199fc16c2865473574f1247b05defdfa6759",
          "md5": "48c2a45c5aa213c72aa4c6d4a1d3b95d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myplugin-1.0.jar",
          "url": "myplugin-1.0.jar",
          "size": 16154,
          "sha512": "5c2dd4f2cecbf8101412b75fa957bd4b916873b69c08b49f4ba7b73981b54a36d237521df3980f73c8ecfd6e8c4853f94bead44835f66f79bbf4bb8c53f554ff",
          "sha256": "ed26181a9ee76e1d9ab6303f2ea0e5719ee55c023caec2f742b802aeb58ad0cb",
          "sha1": "470c199fc16c2865473574f1247b05defdfa6759",
          "md5": "48c2a45c5aa213c72aa4c6d4a1d3b95d"
        }
      ]
    }
  ]
}
